# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e2218ff585bd8dc51baa9b5d4a0126355ed11437002c3cc1808d51df6a0ac4e98d1a401bd25f0419439a14f292bdf6197e1e73c407a2bf2c1eff3fb11e650de

test:
  secret_key_base: 1d85b4568a74e9ccd78cc54a790d37d10d1d064942e17ee6bd4930c258c16f2864636c78cd1d5fad44512aac2f2326373ef4891505bdf2d3ff6d541221861f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
